/*
-- PRIMER BLOQUE ANONIMO
SET SERVEROUTPUT ON;
DECLARE -- OPCIONAL

BEGIN

DBMS_OUTPUT.PUT_LINE('Hola PLSQL');

END;

-- BLOQUE ANONIMO USANDO VARIABLE
SET SERVEROUTPUT ON;
DECLARE 
v_holaplsql VARCHAR(25);
BEGIN

v_holaplsql:= 'Hola PLSQL';
DBMS_OUTPUT.PUT_LINE(v_holaplsql);
END;


SET SERVEROUTPUT ON;
DECLARE 
v_holaplsql VARCHAR(25) := 'Hola PLSQL1';
BEGIN
DBMS_OUTPUT.PUT_LINE(v_holaplsql);
v_holaplsql:= 'Hola PLSQL2';
DBMS_OUTPUT.PUT_LINE(v_holaplsql);
END;


-- USANDO HR

SELECT D.DEPARTMENT_NAME, FIRST_NAME, LAST_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D USING(DEPARTMENT_ID)
WHERE EMPLOYEE_ID = 130;

SET SERVEROUTPUT ON;
DECLARE
v_depto DEPARTMENTS.department_name%TYPE;
v_nombreemp EMPLOYEES.first_name%TYPE;
v_apeemp EMPLOYEES.last_name%TYPE;
BEGIN
SELECT D.DEPARTMENT_NAME, FIRST_NAME, LAST_NAME
INTO v_depto, v_nombreemp, v_apeemp -- ASIGNA LOS VALORES A LAS VARIABLES
FROM EMPLOYEES E
JOIN DEPARTMENTS D USING(DEPARTMENT_ID)
WHERE EMPLOYEE_ID = 130;

DBMS_OUTPUT.PUT_LINE('EL EMPLEADO: '|| v_nombreemp || ' ' || v_apeemp 
|| ' TRABAJA EN EL DEPARTAMENTO: ' || v_depto); -- MUESTRA LOS VALORES DE LA CONSULTA
END;

--VARIABLE BIND
SET SERVEROUTPUT ON;
DECLARE
v_depto DEPARTMENTS.department_name%TYPE;
v_nombreemp EMPLOYEES.first_name%TYPE;
v_apeemp EMPLOYEES.last_name%TYPE;
v_emp int := &emp; -- PARA SOLICITAR VALOR POR PANTALLA EN FORMATO NUMERICO
BEGIN
SELECT D.DEPARTMENT_NAME, FIRST_NAME, LAST_NAME
INTO v_depto, v_nombreemp, v_apeemp -- ASIGNA LOS VALORES A LAS VARIABLES
FROM EMPLOYEES E
JOIN DEPARTMENTS D USING(DEPARTMENT_ID)
WHERE EMPLOYEE_ID = v_emp;

DBMS_OUTPUT.PUT_LINE('EL EMPLEADO: '|| v_nombreemp || ' ' || v_apeemp 
|| ' TRABAJA EN EL DEPARTAMENTO: ' || v_depto); -- MUESTRA LOS VALORES DE LA CONSULTA

EXCEPTION -- EXCEPCION O CONTROL DE EXCEPCIONES (UNIDAD 2)
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR!!!!');
END;
*/


DECLARE
VARIABLE v_emp INT;
BEGIN
SELECT salary INTO :v_emp FROM EMPLOYEES WHERE EMPLOYEE_ID = 120;
END;
/
PRINT v_emp;

